import { Component } from '@angular/core';

@Component({
  selector: 'app-friends',
  templateUrl: './friends.component.html',
  styleUrls: ['./friends.component.scss'],
})
export class FriendsComponent {
  friendsArray = [
    {
      img: '1.jpg',
      name: 'Omar Mansor',
      title: 'JavaScript Developer',
      friends: 99,
      projects: 15,
      articles: 25,
      joined: '02/10/2021',
    },
    {
      img: '2.jpg',
      name: 'Omar Fathy',
      title: 'Cloud Developer',
      friends: 30,
      projects: 11,
      articles: 12,
      joined: '02/08/2020',
    },
    {
      img: '3.jpg',
      name: 'Omar Ahmed',
      title: 'Mobile Developer',
      friends: 80,
      projects: 20,
      articles: 18,
      joined: '02/06/2020',
    },
    {
      img: '4.jpg',
      name: 'Shady Nabil',
      title: 'Back-End Developer',
      friends: 70,
      projects: 30,
      articles: 18,
      joined: '28/06/2020',
    },
    {
      img: '5.jpg',
      name: 'Mohamed Ibrahim',
      title: 'Algorithm Developer',
      friends: 80,
      projects: 30,
      articles: 18,
      joined: '28/08/2020',
    },
    {
      img: '6.jpg',
      name: 'Amr Hendawy',
      title: 'Back-End Developer',
      friends: 70,
      projects: 30,
      articles: 18,
      joined: '28/06/2020',
    },
    {
      img: '7.jpg',
      name: 'Mahmoud Adel',
      title: 'Cloud Developer',
      friends: 30,
      projects: 11,
      articles: 12,
      joined: '02/08/2020',
    },
    {
      img: '8.jpg',
      name: 'Ahmed Abuzaid',
      title: 'Content Creator',
      friends: 80,
      projects: 30,
      articles: 18,
      joined: '28/08/2020',
    },
    {
      img: '9.jpg',
      name: 'Gareeb Elshiekh',
      title: 'JavaScript Developer',
      friends: 90,
      projects: 15,
      articles: 25,
      joined: '02/10/2020',
    },
    {
      img: '10.jpg',
      name: 'Hamza',
      title: 'Front-End Developer',
      friends: 80,
      projects: 20,
      articles: 18,
      joined: '02/06/2020',
    },
  ];
}
