import { Component } from '@angular/core';

@Component({
  selector: 'app-files',
  templateUrl: './files.component.html',
  styleUrls: ['./files.component.scss'],
})
export class FilesComponent {
  fileStatistics = [
    {
      type: 'PDF Files',
      icon: 'fa-regular fa-file-pdf fa-lg blue center-flex c-blue icon',
      count: '130',
      size: '6.5GB',
    },
    {
      type: 'Images',
      icon: 'fa-regular fa-images fa-lg green center-flex c-green icon',
      count: '115 Files',
      size: '3.5GB',
    },
    {
      type: 'Word Files',
      icon: 'fa-regular fa-file-word fa-lg red center-flex c-red icon',
      count: '110 Files',
      size: '3.2GB',
    },
    {
      type: 'CSV Files',
      icon: 'fa-solid fa-file-csv fa-lg orange center-flex c-orange icon',
      count: '99 Files',
      size: '2.9GB',
    },
  ];

  files = [
    {
      name: 'file-01.pdf',
      author: 'Author1',
      date: '20/06/2020',
      size: '5.5MB',
      img: 'pdf.svg',
    },
    {
      name: 'file-02.avi',
      author: 'Author2',
      date: '12/03/2021',
      size: '12.5MB',
      img: 'avi.svg',
    },
    {
      name: 'file-03.eps',
      author: 'Author3',
      date: '08/11/2019',
      size: '2.7MB',
      img: 'eps.svg',
    },
    {
      name: 'file-04.psd',
      author: 'Author4',
      date: '22/07/2021',
      size: '15.1MB',
      img: 'psd.svg',
    },
    {
      name: 'file-05.dll',
      author: 'Author5',
      date: '15/01/2022',
      size: '2.2MB',
      img: 'dll.svg',
    },
    {
      name: 'file-06.png',
      author: 'Author6',
      date: '30/09/2020',
      size: '1.1MB',
      img: 'png.svg',
    },
    {
      name: 'file-07.dll',
      author: 'Author7',
      date: '10/04/2019',
      size: '2.2MB',
      img: 'dll.svg',
    },
    {
      name: 'file-08.png',
      author: 'Author8',
      date: '28/02/2020',
      size: '1.1MB',
      img: 'png.svg',
    },
    {
      name: 'file-09.psd',
      author: 'Author9',
      date: '17/06/2018',
      size: '15.1MB',
      img: 'psd.svg',
    },
    {
      name: 'file-10.pdf',
      author: 'Author10',
      date: '05/08/2021',
      size: '5.5MB',
      img: 'pdf.svg',
    },
    {
      name: 'file-11.pdf',
      author: 'Author11',
      date: '11/02/2017',
      size: '4.8MB',
      img: 'pdf.svg',
    },
    {
      name: 'file-12.avi',
      author: 'Author12',
      date: '25/07/2019',
      size: '13.2MB',
      img: 'avi.svg',
    },
    {
      name: 'file-13.eps',
      author: 'Author13',
      date: '03/12/2020',
      size: '3.1MB',
      img: 'eps.svg',
    },
    {
      name: 'file-14.psd',
      author: 'Author14',
      date: '14/11/2021',
      size: '16.4MB',
      img: 'psd.svg',
    },
    {
      name: 'file-15.dll',
      author: 'Author15',
      date: '09/03/2022',
      size: '2.6MB',
      img: 'dll.svg',
    },
    {
      name: 'file-16.png',
      author: 'Author16',
      date: '27/08/2020',
      size: '1.3MB',
      img: 'png.svg',
    },
    {
      name: 'file-17.dll',
      author: 'Author17',
      date: '05/06/2019',
      size: '2.1MB',
      img: 'dll.svg',
    },
    {
      name: 'file-18.png',
      author: 'Author18',
      date: '19/04/2020',
      size: '1.5MB',
      img: 'png.svg',
    },
    {
      name: 'file-19.psd',
      author: 'Author19',
      date: '12/09/2018',
      size: '15.8MB',
      img: 'psd.svg',
    },
    {
      name: 'file-20.pdf',
      author: 'Author20',
      date: '20/12/2021',
      size: '5.2MB',
      img: 'pdf.svg',
    },
    {
      name: 'file-21.pdf',
      author: 'Author21',
      date: '17/01/2016',
      size: '6.0MB',
      img: 'pdf.svg',
    },
    {
      name: 'file-22.avi',
      author: 'Author22',
      date: '06/11/2020',
      size: '14.7MB',
      img: 'avi.svg',
    },
    {
      name: 'file-23.eps',
      author: 'Author23',
      date: '15/10/2019',
      size: '3.4MB',
      img: 'eps.svg',
    },
    {
      name: 'file-24.psd',
      author: 'Author24',
      date: '28/07/2022',
      size: '17.2MB',
      img: 'psd.svg',
    },
  ];
}
